agent:
  name: sac
  class: pytorch_mbpo.pytorch_sac.agent.sac.SACAgent
  params:
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    discount: 0.99
    init_temperature: 1.
    target_entropy: ???
    alpha_lr: 3e-4
    alpha_betas: [0.9, 0.999]
    actor_lr: 3e-4
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_update_frequency: 1
    critic_lr: 3e-4
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 1
    batch_size: 256
    
double_q_critic:
  class: pytorch_mbpo.pytorch_sac.agent.critic.DoubleQCritic
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_dim: 256
    hidden_depth: 2
    init: keras
    
diag_gaussian_actor:
  class: pytorch_mbpo.pytorch_sac.agent.actor.DiagGaussianActor
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_depth: 2
    hidden_dim: 256
    log_std_bounds: [-5, 2]